/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import Utilities.SQLDetails;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Alex
 */
public class FinanceKeeper extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst = null;
    ResultSet rs = null;
    static String password = "";
    String Income;
    
    ArrayList<String> user_raw = new ArrayList<>();
    String[] userid = new String[user_raw.size()];
    
    public static String hashme() {

        String hashed = BCrypt.hashpw(password, BCrypt.gensalt());

        return hashed;
    }
    /**
     * Creates new form FinanceKeeper
     */
    public FinanceKeeper() {
        initComponents();
        mNav.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAED = new javax.swing.ButtonGroup();
        pMain = new javax.swing.JPanel();
        pNewLogin = new javax.swing.JPanel();
        lblNewLogin = new javax.swing.JLabel();
        txtNewID = new javax.swing.JTextField();
        pfNewPassword = new javax.swing.JPasswordField();
        pfCheckPassword = new javax.swing.JPasswordField();
        btnSubmitL = new javax.swing.JButton();
        lblpwError = new javax.swing.JLabel();
        pLogin = new javax.swing.JPanel();
        pnlAccLogin = new javax.swing.JPanel();
        lblLoginTitle = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblNewAcc = new javax.swing.JLabel();
        pHome = new javax.swing.JPanel();
        lblOverview = new javax.swing.JLabel();
        pnlStatistics = new javax.swing.JPanel();
        lblUtilityTitle = new javax.swing.JLabel();
        lblIncomeTitle = new javax.swing.JLabel();
        lblIncomeReturn = new javax.swing.JLabel();
        lblUtilityReturn = new javax.swing.JLabel();
        lblExpensesTitle = new javax.swing.JLabel();
        lblExpReturn = new javax.swing.JLabel();
        lblSavedTitle = new javax.swing.JLabel();
        lblSavedReturn = new javax.swing.JLabel();
        pnlOptions = new javax.swing.JPanel();
        btnAccounts = new javax.swing.JButton();
        btnUtility = new javax.swing.JButton();
        btnExpenses = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        pAccounts = new javax.swing.JPanel();
        lblAccount = new javax.swing.JLabel();
        pnlAccDetails = new javax.swing.JPanel();
        txtAccID = new javax.swing.JTextField();
        txtForename = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        rbAdd = new javax.swing.JRadioButton();
        rbEdit = new javax.swing.JRadioButton();
        rbDelete = new javax.swing.JRadioButton();
        btnSubmit = new javax.swing.JButton();
        pnlIncome = new javax.swing.JPanel();
        txtIncome = new javax.swing.JTextField();
        txtTFA = new javax.swing.JTextField();
        txtTT = new javax.swing.JTextField();
        txtIT = new javax.swing.JTextField();
        txtNI = new javax.swing.JTextField();
        txtTD = new javax.swing.JTextField();
        txtNW = new javax.swing.JTextField();
        pUtilities = new javax.swing.JPanel();
        lblUtilities = new javax.swing.JLabel();
        spUtilities = new javax.swing.JScrollPane();
        tblUtilities = new javax.swing.JTable();
        pUtilDetails = new javax.swing.JPanel();
        txtItemName = new javax.swing.JTextField();
        txtItemValue = new javax.swing.JTextField();
        cbBillingCycle = new javax.swing.JComboBox<>();
        rbAddU = new javax.swing.JRadioButton();
        rbEditU = new javax.swing.JRadioButton();
        rbDeleteU = new javax.swing.JRadioButton();
        btnSubmitU = new javax.swing.JButton();
        pExpenses = new javax.swing.JPanel();
        spExpenses = new javax.swing.JScrollPane();
        tblExpenses = new javax.swing.JTable();
        lblExpenses = new javax.swing.JLabel();
        pExpDetails = new javax.swing.JPanel();
        txtExpName = new javax.swing.JTextField();
        txtExpValue = new javax.swing.JTextField();
        rbAddE = new javax.swing.JRadioButton();
        rbEditE = new javax.swing.JRadioButton();
        rbDeleteE = new javax.swing.JRadioButton();
        btnSubmitE = new javax.swing.JButton();
        mbMenuBar = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        mNav = new javax.swing.JMenu();
        miHome = new javax.swing.JMenuItem();
        miAccounts = new javax.swing.JMenuItem();
        miUtilities = new javax.swing.JMenuItem();
        miExpenses = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pMain.setLayout(new java.awt.CardLayout());

        lblNewLogin.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblNewLogin.setText("New Login");

        txtNewID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNewID.setForeground(java.awt.Color.gray);
        txtNewID.setText("Enter your chosen ID...");
        txtNewID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewIDFocusLost(evt);
            }
        });
        txtNewID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewIDKeyReleased(evt);
            }
        });

        pfNewPassword.setText("Password");
        pfNewPassword.setToolTipText("Enter your chosen password...");
        pfNewPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfNewPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfNewPasswordFocusLost(evt);
            }
        });

        pfCheckPassword.setText("Password");
        pfCheckPassword.setToolTipText("Please retype your password...");
        pfCheckPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfCheckPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfCheckPasswordFocusLost(evt);
            }
        });

        btnSubmitL.setText("Submit");
        btnSubmitL.setEnabled(false);
        btnSubmitL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitLActionPerformed(evt);
            }
        });

        lblpwError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpwError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pNewLoginLayout = new javax.swing.GroupLayout(pNewLogin);
        pNewLogin.setLayout(pNewLoginLayout);
        pNewLoginLayout.setHorizontalGroup(
            pNewLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNewLoginLayout.createSequentialGroup()
                .addGroup(pNewLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNewLoginLayout.createSequentialGroup()
                        .addGroup(pNewLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pNewLoginLayout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(lblNewLogin))
                            .addGroup(pNewLoginLayout.createSequentialGroup()
                                .addGap(316, 316, 316)
                                .addComponent(btnSubmitL))
                            .addGroup(pNewLoginLayout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addGroup(pNewLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNewID, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(pfNewPassword)
                                    .addComponent(pfCheckPassword))))
                        .addGap(0, 285, Short.MAX_VALUE))
                    .addGroup(pNewLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblpwError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pNewLoginLayout.setVerticalGroup(
            pNewLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNewLoginLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(lblNewLogin)
                .addGap(46, 46, 46)
                .addComponent(txtNewID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(pfNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pfCheckPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnSubmitL)
                .addGap(18, 18, 18)
                .addComponent(lblpwError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pMain.add(pNewLogin, "pNewLogin");

        lblLoginTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblLoginTitle.setText("Finance Keeper Login");
        lblLoginTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtUserID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUserID.setForeground(java.awt.Color.gray);
        txtUserID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserID.setText("Enter User ID...");
        txtUserID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserIDFocusLost(evt);
            }
        });

        pfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pfPassword.setText("Password");
        pfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfPasswordFocusLost(evt);
            }
        });

        btnLogin.setMnemonic('L');
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnExit.setMnemonic('E');
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblNewAcc.setForeground(java.awt.Color.blue);
        lblNewAcc.setText("Create an Account?...");
        lblNewAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewAccMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAccLoginLayout = new javax.swing.GroupLayout(pnlAccLogin);
        pnlAccLogin.setLayout(pnlAccLoginLayout);
        pnlAccLoginLayout.setHorizontalGroup(
            pnlAccLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccLoginLayout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addGroup(pnlAccLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAccLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccLoginLayout.createSequentialGroup()
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccLoginLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNewAcc)
                            .addGap(54, 54, 54)))
                    .addComponent(lblLoginTitle))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlAccLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUserID)
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        pnlAccLoginLayout.setVerticalGroup(
            pnlAccLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccLoginLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblLoginTitle)
                .addGap(50, 50, 50)
                .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(pnlAccLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnExit))
                .addGap(18, 18, 18)
                .addComponent(lblNewAcc)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(pnlAccLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(211, 211, 211))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(pnlAccLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pMain.add(pLogin, "pLogin");

        lblOverview.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblOverview.setText("Overview");

        lblUtilityTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblUtilityTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtilityTitle.setText("Total Utilities");
        lblUtilityTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIncomeTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblIncomeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIncomeTitle.setText("Total Income");
        lblIncomeTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIncomeReturn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIncomeReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIncomeReturn.setText("Waiting for Total Income Value...");
        lblIncomeReturn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        lblUtilityReturn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUtilityReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtilityReturn.setText("Waiting for Total Utilities Value...");
        lblUtilityReturn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        lblExpensesTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblExpensesTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExpensesTitle.setText("Total Expenses");
        lblExpensesTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblExpReturn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExpReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExpReturn.setText("Waiting for Total Expenses Value...");
        lblExpReturn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        lblSavedTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSavedTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSavedTitle.setText("Total Saved");
        lblSavedTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSavedReturn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSavedReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSavedReturn.setText("Waiting for Total Saved Income...");
        lblSavedReturn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout pnlStatisticsLayout = new javax.swing.GroupLayout(pnlStatistics);
        pnlStatistics.setLayout(pnlStatisticsLayout);
        pnlStatisticsLayout.setHorizontalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatisticsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSavedReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblExpReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlStatisticsLayout.createSequentialGroup()
                        .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUtilityTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIncomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExpensesTitle)
                            .addComponent(lblSavedTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblUtilityReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIncomeReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlStatisticsLayout.setVerticalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatisticsLayout.createSequentialGroup()
                .addComponent(lblIncomeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIncomeReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUtilityTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUtilityReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExpensesTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExpReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSavedTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSavedReturn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAccounts.setMnemonic('A');
        btnAccounts.setText("Accounts");
        btnAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountsActionPerformed(evt);
            }
        });

        btnUtility.setMnemonic('U');
        btnUtility.setText("Utilities");
        btnUtility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtilityActionPerformed(evt);
            }
        });

        btnExpenses.setMnemonic('E');
        btnExpenses.setText("Expenses");
        btnExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpensesActionPerformed(evt);
            }
        });

        btnLogout.setMnemonic('L');
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnExit1.setMnemonic('E');
        btnExit1.setText("Exit");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOptionsLayout = new javax.swing.GroupLayout(pnlOptions);
        pnlOptions.setLayout(pnlOptionsLayout);
        pnlOptionsLayout.setHorizontalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUtility, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        pnlOptionsLayout.setVerticalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUtility, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pHomeLayout = new javax.swing.GroupLayout(pHome);
        pHome.setLayout(pHomeLayout);
        pHomeLayout.setHorizontalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHomeLayout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblOverview)
                    .addComponent(pnlStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnlOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        pHomeLayout.setVerticalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHomeLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblOverview)
                .addGap(18, 18, 18)
                .addGroup(pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pMain.add(pHome, "pHome");

        lblAccount.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccount.setText("Account");

        pnlAccDetails.setPreferredSize(new java.awt.Dimension(187, 257));

        txtAccID.setEditable(false);
        txtAccID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAccID.setForeground(java.awt.Color.gray);
        txtAccID.setText("Account ID...");

        txtForename.setEditable(false);
        txtForename.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtForename.setForeground(java.awt.Color.gray);
        txtForename.setText("Forename...");

        txtSurname.setEditable(false);
        txtSurname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSurname.setForeground(java.awt.Color.gray);
        txtSurname.setText("Surname...");

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setForeground(java.awt.Color.gray);
        txtEmail.setText("Email...");

        bgAED.add(rbAdd);
        rbAdd.setText("Add Details");

        bgAED.add(rbEdit);
        rbEdit.setText("Edit Details");

        bgAED.add(rbDelete);
        rbDelete.setText("Delete Account");

        btnSubmit.setText("Submit");

        javax.swing.GroupLayout pnlAccDetailsLayout = new javax.swing.GroupLayout(pnlAccDetails);
        pnlAccDetails.setLayout(pnlAccDetailsLayout);
        pnlAccDetailsLayout.setHorizontalGroup(
            pnlAccDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAccDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAccID, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addComponent(txtForename, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSurname)
                    .addComponent(txtEmail))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAccDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        pnlAccDetailsLayout.setVerticalGroup(
            pnlAccDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAccID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtForename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAccDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAccDetailsLayout.createSequentialGroup()
                        .addComponent(rbAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDelete))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );

        pnlIncome.setPreferredSize(new java.awt.Dimension(187, 45));

        txtIncome.setEditable(false);
        txtIncome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIncome.setForeground(java.awt.Color.gray);
        txtIncome.setText("Income...");

        txtTFA.setEditable(false);
        txtTFA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTFA.setForeground(java.awt.Color.gray);
        txtTFA.setText("Tax Free Allowance...");

        txtTT.setEditable(false);
        txtTT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTT.setForeground(java.awt.Color.gray);
        txtTT.setText("Total Taxable...");

        txtIT.setEditable(false);
        txtIT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIT.setForeground(java.awt.Color.gray);
        txtIT.setText("Income Tax...");

        txtNI.setEditable(false);
        txtNI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNI.setForeground(java.awt.Color.gray);
        txtNI.setText("National Insurance...");

        txtTD.setEditable(false);
        txtTD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTD.setForeground(java.awt.Color.gray);
        txtTD.setText("Total Deductions...");

        txtNW.setEditable(false);
        txtNW.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNW.setForeground(java.awt.Color.gray);
        txtNW.setText("Net Wage...");

        javax.swing.GroupLayout pnlIncomeLayout = new javax.swing.GroupLayout(pnlIncome);
        pnlIncome.setLayout(pnlIncomeLayout);
        pnlIncomeLayout.setHorizontalGroup(
            pnlIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIncomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIncome)
                    .addComponent(txtTFA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(txtTT)
                    .addComponent(txtIT)
                    .addComponent(txtNI)
                    .addComponent(txtTD)
                    .addComponent(txtNW))
                .addContainerGap())
        );
        pnlIncomeLayout.setVerticalGroup(
            pnlIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIncomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTFA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pAccountsLayout = new javax.swing.GroupLayout(pAccounts);
        pAccounts.setLayout(pAccountsLayout);
        pAccountsLayout.setHorizontalGroup(
            pAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAccDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pAccountsLayout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(lblAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pAccountsLayout.setVerticalGroup(
            pAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(pAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlIncome, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(pnlAccDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                .addContainerGap())
        );

        pMain.add(pAccounts, "pAccounts");

        lblUtilities.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblUtilities.setText("Utilities");

        tblUtilities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Value", "Billing Cycle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spUtilities.setViewportView(tblUtilities);

        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtItemName.setForeground(java.awt.Color.gray);
        txtItemName.setText("Enter Item Name...");

        txtItemValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtItemValue.setForeground(java.awt.Color.gray);
        txtItemValue.setText("Enter Item Value...");

        cbBillingCycle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Billing Cycle...", "N/A", "1 Month", "3 Month", "4 Month", "Annual" }));
        cbBillingCycle.setToolTipText("If it is not a set cycle then select N/A.");

        bgAED.add(rbAddU);
        rbAddU.setText("Add Item");

        bgAED.add(rbEditU);
        rbEditU.setText("Edit Item");

        bgAED.add(rbDeleteU);
        rbDeleteU.setText("Delete Item");

        btnSubmitU.setText("Submit");

        javax.swing.GroupLayout pUtilDetailsLayout = new javax.swing.GroupLayout(pUtilDetails);
        pUtilDetails.setLayout(pUtilDetailsLayout);
        pUtilDetailsLayout.setHorizontalGroup(
            pUtilDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUtilDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pUtilDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemName)
                    .addComponent(txtItemValue)
                    .addComponent(cbBillingCycle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pUtilDetailsLayout.createSequentialGroup()
                        .addGroup(pUtilDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbDeleteU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbEditU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbAddU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pUtilDetailsLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnSubmitU, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        pUtilDetailsLayout.setVerticalGroup(
            pUtilDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUtilDetailsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtItemValue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbBillingCycle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbAddU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbEditU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbDeleteU)
                .addGap(18, 18, 18)
                .addComponent(btnSubmitU, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pUtilitiesLayout = new javax.swing.GroupLayout(pUtilities);
        pUtilities.setLayout(pUtilitiesLayout);
        pUtilitiesLayout.setHorizontalGroup(
            pUtilitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUtilitiesLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(lblUtilities)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUtilitiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pUtilDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spUtilities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pUtilitiesLayout.setVerticalGroup(
            pUtilitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUtilitiesLayout.createSequentialGroup()
                .addComponent(lblUtilities)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pUtilitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spUtilities, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addGroup(pUtilitiesLayout.createSequentialGroup()
                        .addComponent(pUtilDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pMain.add(pUtilities, "pUtilities");

        tblExpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expense Item", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spExpenses.setViewportView(tblExpenses);

        lblExpenses.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblExpenses.setText("Expenses");

        txtExpName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtExpName.setForeground(java.awt.Color.gray);
        txtExpName.setText("Enter Expense name...");

        txtExpValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtExpValue.setForeground(java.awt.Color.gray);
        txtExpValue.setText("Enter Expense Value...");

        bgAED.add(rbAddE);
        rbAddE.setText("Add Details");

        bgAED.add(rbEditE);
        rbEditE.setText("Edit Details");

        bgAED.add(rbDeleteE);
        rbDeleteE.setText("Delete Account");

        btnSubmitE.setText("Submit");

        javax.swing.GroupLayout pExpDetailsLayout = new javax.swing.GroupLayout(pExpDetails);
        pExpDetails.setLayout(pExpDetailsLayout);
        pExpDetailsLayout.setHorizontalGroup(
            pExpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pExpDetailsLayout.createSequentialGroup()
                .addGroup(pExpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pExpDetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pExpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExpName)
                            .addComponent(txtExpValue, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)))
                    .addGroup(pExpDetailsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pExpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rbDeleteE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbEditE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbAddE, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pExpDetailsLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnSubmitE, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pExpDetailsLayout.setVerticalGroup(
            pExpDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pExpDetailsLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(txtExpName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtExpValue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(rbAddE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbEditE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbDeleteE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmitE, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pExpensesLayout = new javax.swing.GroupLayout(pExpenses);
        pExpenses.setLayout(pExpensesLayout);
        pExpensesLayout.setHorizontalGroup(
            pExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pExpensesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pExpDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pExpensesLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(lblExpenses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pExpensesLayout.setVerticalGroup(
            pExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pExpensesLayout.createSequentialGroup()
                .addComponent(lblExpenses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pExpDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pMain.add(pExpenses, "pExpenses");

        mFile.setMnemonic('F');
        mFile.setText("File");

        miLogout.setMnemonic('L');
        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mFile.add(miLogout);

        miExit.setMnemonic('E');
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mFile.add(miExit);

        mbMenuBar.add(mFile);

        mNav.setMnemonic('N');
        mNav.setText("Navigate");

        miHome.setMnemonic('H');
        miHome.setText("Home");
        miHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHomeActionPerformed(evt);
            }
        });
        mNav.add(miHome);

        miAccounts.setMnemonic('A');
        miAccounts.setText("Accounts");
        miAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAccountsActionPerformed(evt);
            }
        });
        mNav.add(miAccounts);

        miUtilities.setMnemonic('U');
        miUtilities.setText("Utilities");
        miUtilities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUtilitiesActionPerformed(evt);
            }
        });
        mNav.add(miUtilities);

        miExpenses.setMnemonic('E');
        miExpenses.setText("Expenses");
        miExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExpensesActionPerformed(evt);
            }
        });
        mNav.add(miExpenses);

        mbMenuBar.add(mNav);

        mHelp.setMnemonic('H');
        mHelp.setText("Help");
        mHelp.setAlignmentX(1.0F);
        mHelp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        miAbout.setMnemonic('A');
        miAbout.setText("About");
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        mHelp.add(miAbout);

        mbMenuBar.add(mHelp);

        setJMenuBar(mbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(FinanceKeeper.this, "Version: v1.0"+"\n"+"Created By: Alex Morrison", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_miAboutActionPerformed

    private void miUtilitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUtilitiesActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pUtilities");
        miHome.setEnabled(true);
        miAccounts.setEnabled(true);
        miUtilities.setEnabled(false);
        miExpenses.setEnabled(true);
    }//GEN-LAST:event_miUtilitiesActionPerformed

    private void miAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAccountsActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pAccounts");
        miHome.setEnabled(true);
        miAccounts.setEnabled(false);
        miUtilities.setEnabled(true);
        miExpenses.setEnabled(true);
    }//GEN-LAST:event_miAccountsActionPerformed

    private void miHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHomeActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pHome");
        miHome.setEnabled(false);
        miAccounts.setEnabled(true);
        miUtilities.setEnabled(true);
        miExpenses.setEnabled(true);
        
    }//GEN-LAST:event_miHomeActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_miExitActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
        mNav.setEnabled(false);
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pLogin");
        
    }//GEN-LAST:event_miLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try{
            CardLayout card = (CardLayout)pMain.getLayout();
            int flag  = 1;
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/FinanceDB", "GateKeeper", "EyeOfSauron");
            Statement state = conn.createStatement();
            ResultSet res = state.executeQuery("Select ID, PASSWORD from LOGIN");
            while(res.next()) {
                if(res.getString(1).equals(txtUserID.getText()) && res.getString(2).equals(pfPassword.getText())) {
                    flag = 0;
                    break;
                }
            }
            if(flag == 0) {
                mNav.setEnabled(true);
                card.show(pMain, "pHome");
                miHome.setEnabled(false);
                txtUserID.setText("");
                pfPassword.setText("");
                btnLogin.setEnabled(false);
            }else {
                JOptionPane.showMessageDialog(null, "Login Error"+"\n"+"Reason: The User ID and/or Password was incorrect.", "Login Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void pfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPasswordFocusLost
        // TODO add your handling code here:
        if(pfPassword.getText().equals("")){
            pfPassword.setText("Password");
        }
    }//GEN-LAST:event_pfPasswordFocusLost

    private void pfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPasswordFocusGained
        // TODO add your handling code here:
        if(pfPassword.getText().equals("Password")){
            pfPassword.setText("");
        }
    }//GEN-LAST:event_pfPasswordFocusGained

    private void txtUserIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserIDFocusLost
        // TODO add your handling code here:
        if(txtUserID.getText().equals("")) {
            txtUserID.setText("Enter User ID...");
            txtUserID.setForeground(Color.LIGHT_GRAY);
            btnLogin.setEnabled(false);
        }else if(txtUserID.getText().equals("Enter User ID...")) {
            btnLogin.setEnabled(false);
        }else {
            btnLogin.setEnabled(true);
        }
    }//GEN-LAST:event_txtUserIDFocusLost

    private void txtUserIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserIDFocusGained
        // TODO add your handling code here:
        if(txtUserID.getText().equals("Enter User ID...")) {
            btnLogin.setEnabled(false);
            txtUserID.setText("");
            txtUserID.setForeground(Color.BLACK);
        }else {
            btnLogin.setEnabled(true);
        }
    }//GEN-LAST:event_txtUserIDFocusGained

    private void miExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExpensesActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pExpenses");
        miHome.setEnabled(true);
        miAccounts.setEnabled(true);
        miUtilities.setEnabled(true);
        miExpenses.setEnabled(false);
    }//GEN-LAST:event_miExpensesActionPerformed

    private void lblNewAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewAccMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pNewLogin");
    }//GEN-LAST:event_lblNewAccMouseClicked

    private void btnAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountsActionPerformed
        // TODO add your handling code here:
        try {
            conn = DriverManager.getConnection(SQLDetails.URL, SQLDetails.USER, SQLDetails.PASS);
            String Accid = txtUserID.getText();
            String sql = "SELECT * FROM `accounts` WHERE `AccountID` =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, Accid);
            rs = pst.executeQuery();
            Account acc = new Account();
            if (rs.next()) {
                String ID = rs.getString("AccountID");
                txtAccID.setText(ID);
                txtAccID.setForeground(Color.black);
                String FN = rs.getString("Forename");
                txtForename.setText(FN);
                txtForename.setForeground(Color.black);
                String LN = rs.getString("Surname");
                txtSurname.setText(LN);
                txtSurname.setForeground(Color.black);
                String EM = rs.getString("Email");
                txtEmail.setText(EM);
                txtEmail.setForeground(Color.black);
                String INC = rs.getString("Income");
                txtIncome.setText(INC);
                txtIncome.setForeground(Color.black);
                Income = txtIncome.getText();
            } else {
                JOptionPane.showMessageDialog(null, "Record does not exist");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        Account Acc = new Account();
        txtTFA.setText(Acc.getTfa());
        txtTT.setText(Acc.getTotaltax());
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pAccounts");
        miHome.setEnabled(true);
        miAccounts.setEnabled(false);
        miUtilities.setEnabled(true);
        miExpenses.setEnabled(true);
    }//GEN-LAST:event_btnAccountsActionPerformed

    private void btnUtilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtilityActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pUtilities");
        miHome.setEnabled(true);
        miAccounts.setEnabled(true);
        miUtilities.setEnabled(false);
        miExpenses.setEnabled(true);
    }//GEN-LAST:event_btnUtilityActionPerformed

    private void btnExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpensesActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pExpenses");
        miHome.setEnabled(true);
        miAccounts.setEnabled(true);
        miUtilities.setEnabled(true);
        miExpenses.setEnabled(false);
    }//GEN-LAST:event_btnExpensesActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        mNav.setEnabled(false);
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pLogin");
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void txtNewIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewIDFocusGained
        // TODO add your handling code here:
        if(txtNewID.getText().equals("Enter your chosen ID...")) {
            txtNewID.setText("");
            txtNewID.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNewIDFocusGained

    private void txtNewIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewIDFocusLost
        // TODO add your handling code here:
        if(txtNewID.getText().equals("")) {
            txtNewID.setText("Enter your chosen ID...");
            txtNewID.setForeground(Color.gray);
        }else if(pfCheckPassword.getText().equals(pfNewPassword.getText()) && !txtNewID.getText().equals(" ") && !txtNewID.getText().equals("Enter your chosen ID...")) {
            lblpwError.setText("");
            pfNewPassword.setForeground(Color.green);
            pfCheckPassword.setForeground(Color.green);
            btnSubmitL.setEnabled(true);
        }else if(!pfCheckPassword.getText().equals(pfNewPassword.getText()) && txtNewID.getText().equals("Enter your chosen ID...") || txtNewID.getText().equals(" ")) {
            pfNewPassword.setForeground(Color.red);
            pfCheckPassword.setForeground(Color.red);
            lblpwError.setText("Please enter a valid Account ID! Passwords do not match!");
            btnSubmitL.setEnabled(false);
        }else if(!pfCheckPassword.getText().equals(pfNewPassword.getText())) {
            pfNewPassword.setForeground(Color.red);
            pfCheckPassword.setForeground(Color.red);
            lblpwError.setText("Passwords do not match!");
            btnSubmitL.setEnabled(false);
        }else {
            pfNewPassword.setForeground(Color.green);
            pfCheckPassword.setForeground(Color.green);
            lblpwError.setText("Please enter a valid Account ID!");
            btnSubmitL.setEnabled(false);
        }
    }//GEN-LAST:event_txtNewIDFocusLost

    private void pfNewPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfNewPasswordFocusGained
        // TODO add your handling code here:
        if(pfNewPassword.getText().equals("Password")) {
            pfNewPassword.setText("");
        }
    }//GEN-LAST:event_pfNewPasswordFocusGained

    private void pfNewPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfNewPasswordFocusLost
        // TODO add your handling code here:
        if(pfNewPassword.getText().equals("")) {
            pfNewPassword.setText("Password");
        }else if(pfCheckPassword.getText().equals(pfNewPassword.getText()) && !txtNewID.getText().equals(" ") && !txtNewID.getText().equals("Enter your chosen ID...")) {
            lblpwError.setText("");
            pfNewPassword.setForeground(Color.green);
            pfCheckPassword.setForeground(Color.green);
            btnSubmitL.setEnabled(true);
        }else if(!pfCheckPassword.getText().equals(pfNewPassword.getText()) && txtNewID.getText().equals("Enter your chosen ID...") || txtNewID.getText().equals(" ")) {
            pfNewPassword.setForeground(Color.red);
            pfCheckPassword.setForeground(Color.red);
            lblpwError.setText("Please enter a valid Account ID! Passwords do not match!");
            btnSubmitL.setEnabled(false);
        }else if(!pfCheckPassword.getText().equals(pfNewPassword.getText())) {
            pfNewPassword.setForeground(Color.red);
            pfCheckPassword.setForeground(Color.red);
            lblpwError.setText("Passwords do not match!");
            btnSubmitL.setEnabled(false);
        }else {
            pfNewPassword.setForeground(Color.green);
            pfCheckPassword.setForeground(Color.green);
            lblpwError.setText("Please enter a valid Account ID!");
            btnSubmitL.setEnabled(false);
        }
    }//GEN-LAST:event_pfNewPasswordFocusLost

    private void pfCheckPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfCheckPasswordFocusGained
        // TODO add your handling code here:
        if(pfCheckPassword.getText().equals("Password")) {
            pfCheckPassword.setText("");
        }
    }//GEN-LAST:event_pfCheckPasswordFocusGained

    private void pfCheckPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfCheckPasswordFocusLost
        // TODO add your handling code here:
        if(pfCheckPassword.getText().equals("")) {
            pfCheckPassword.setText("Password");
        }else if(pfCheckPassword.getText().equals(pfNewPassword.getText()) && !txtNewID.getText().equals(" ") && !txtNewID.getText().equals("Enter your chosen ID...")) {
            lblpwError.setText("");
            pfNewPassword.setForeground(Color.green);
            pfCheckPassword.setForeground(Color.green);
            btnSubmitL.setEnabled(true);
        }else if(!pfCheckPassword.getText().equals(pfNewPassword.getText()) && txtNewID.getText().equals("Enter your chosen ID...") || txtNewID.getText().equals(" ")) {
            pfNewPassword.setForeground(Color.red);
            pfCheckPassword.setForeground(Color.red);
            lblpwError.setText("Please enter a valid Account ID! Passwords do not match!");
            btnSubmitL.setEnabled(false);
        }else if(!pfCheckPassword.getText().equals(pfNewPassword.getText())) {
            pfNewPassword.setForeground(Color.red);
            pfCheckPassword.setForeground(Color.red);
            lblpwError.setText("Passwords do not match!");
            btnSubmitL.setEnabled(false);
        }else {
            pfNewPassword.setForeground(Color.green);
            pfCheckPassword.setForeground(Color.green);
            lblpwError.setText("Please enter a valid Account ID!");
            btnSubmitL.setEnabled(false);
        }
    }//GEN-LAST:event_pfCheckPasswordFocusLost

    private void txtNewIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewIDKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNewIDKeyReleased

    private void btnSubmitLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitLActionPerformed
        // TODO add your handling code here:
        try {
            conn = DriverManager.getConnection(SQLDetails.URL, SQLDetails.USER, SQLDetails.PASS);
            pst = conn.prepareStatement("SELECT * FROM accounts;");
            rs = pst.executeQuery();

            while (rs.next()) {
                user_raw.add(rs.getString("AccountID"));
            }

            userid = user_raw.toArray(userid);

            pst.close();
            conn.close();
            password = pfNewPassword.getText();
            hashme();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSubmitLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceKeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceKeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceKeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceKeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinanceKeeper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAED;
    private javax.swing.JButton btnAccounts;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnExpenses;
    public javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmitE;
    private javax.swing.JButton btnSubmitL;
    private javax.swing.JButton btnSubmitU;
    private javax.swing.JButton btnUtility;
    private javax.swing.JComboBox<String> cbBillingCycle;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblExpReturn;
    private javax.swing.JLabel lblExpenses;
    private javax.swing.JLabel lblExpensesTitle;
    private javax.swing.JLabel lblIncomeReturn;
    private javax.swing.JLabel lblIncomeTitle;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblNewAcc;
    private javax.swing.JLabel lblNewLogin;
    private javax.swing.JLabel lblOverview;
    private javax.swing.JLabel lblSavedReturn;
    private javax.swing.JLabel lblSavedTitle;
    private javax.swing.JLabel lblUtilities;
    private javax.swing.JLabel lblUtilityReturn;
    private javax.swing.JLabel lblUtilityTitle;
    private javax.swing.JLabel lblpwError;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenu mNav;
    private javax.swing.JMenuBar mbMenuBar;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miAccounts;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miExpenses;
    private javax.swing.JMenuItem miHome;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miUtilities;
    private javax.swing.JPanel pAccounts;
    private javax.swing.JPanel pExpDetails;
    private javax.swing.JPanel pExpenses;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pNewLogin;
    private javax.swing.JPanel pUtilDetails;
    private javax.swing.JPanel pUtilities;
    private javax.swing.JPasswordField pfCheckPassword;
    private javax.swing.JPasswordField pfNewPassword;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JPanel pnlAccDetails;
    private javax.swing.JPanel pnlAccLogin;
    private javax.swing.JPanel pnlIncome;
    private javax.swing.JPanel pnlOptions;
    private javax.swing.JPanel pnlStatistics;
    private javax.swing.JRadioButton rbAdd;
    private javax.swing.JRadioButton rbAddE;
    private javax.swing.JRadioButton rbAddU;
    private javax.swing.JRadioButton rbDelete;
    private javax.swing.JRadioButton rbDeleteE;
    private javax.swing.JRadioButton rbDeleteU;
    private javax.swing.JRadioButton rbEdit;
    private javax.swing.JRadioButton rbEditE;
    private javax.swing.JRadioButton rbEditU;
    private javax.swing.JScrollPane spExpenses;
    private javax.swing.JScrollPane spUtilities;
    private javax.swing.JTable tblExpenses;
    private javax.swing.JTable tblUtilities;
    private javax.swing.JTextField txtAccID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtExpName;
    private javax.swing.JTextField txtExpValue;
    private javax.swing.JTextField txtForename;
    private javax.swing.JTextField txtIT;
    private javax.swing.JTextField txtIncome;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemValue;
    private javax.swing.JTextField txtNI;
    private javax.swing.JTextField txtNW;
    private javax.swing.JTextField txtNewID;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtTD;
    private javax.swing.JTextField txtTFA;
    private javax.swing.JTextField txtTT;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
