/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Alex
 */
public class FinanceKeeper extends javax.swing.JFrame {
    
    /**
     * Creates new form FinanceKeeper
     */
    public FinanceKeeper() {
        initComponents();
        mNav.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMain = new javax.swing.JPanel();
        pLogin = new javax.swing.JPanel();
        lblLoginTitle = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblNewAcc = new javax.swing.JLabel();
        pHome = new javax.swing.JPanel();
        lblOverview = new javax.swing.JLabel();
        pnlStatistics = new javax.swing.JPanel();
        lblUtilityTitle = new javax.swing.JLabel();
        lblIncomeTitle = new javax.swing.JLabel();
        lblIncomeReturn = new javax.swing.JLabel();
        lblUtilityReturn = new javax.swing.JLabel();
        lblExpensesTitle = new javax.swing.JLabel();
        lblExpReturn = new javax.swing.JLabel();
        lblSavedTitle = new javax.swing.JLabel();
        lblSavedReturn = new javax.swing.JLabel();
        pnlOptions = new javax.swing.JPanel();
        btnAccounts = new javax.swing.JButton();
        btnUtility = new javax.swing.JButton();
        btnExpenses = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        pAccounts = new javax.swing.JPanel();
        pnlAccDetails = new javax.swing.JPanel();
        txtAccID = new javax.swing.JTextField();
        txtForename = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        pnlIncome = new javax.swing.JPanel();
        txtIncome = new javax.swing.JTextField();
        txtTFA = new javax.swing.JTextField();
        txtTT = new javax.swing.JTextField();
        txtIT = new javax.swing.JTextField();
        txtNI = new javax.swing.JTextField();
        txtTD = new javax.swing.JTextField();
        txtNW = new javax.swing.JTextField();
        pUtilities = new javax.swing.JPanel();
        lblUtilities = new javax.swing.JLabel();
        spUtilities = new javax.swing.JScrollPane();
        tblUtilities = new javax.swing.JTable();
        pExpenses = new javax.swing.JPanel();
        spExpenses = new javax.swing.JScrollPane();
        tblExpenses = new javax.swing.JTable();
        lblExpenses = new javax.swing.JLabel();
        pNewLogin = new javax.swing.JPanel();
        lblNewLogin = new javax.swing.JLabel();
        txtNewID = new javax.swing.JTextField();
        pfNewPassword = new javax.swing.JPasswordField();
        pfCheckPassword = new javax.swing.JPasswordField();
        mbMenuBar = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        mEdit = new javax.swing.JMenu();
        mExpenses = new javax.swing.JMenu();
        miAdd = new javax.swing.JMenuItem();
        miEdit = new javax.swing.JMenuItem();
        miDelete = new javax.swing.JMenuItem();
        mNav = new javax.swing.JMenu();
        miHome = new javax.swing.JMenuItem();
        miAccounts = new javax.swing.JMenuItem();
        miUtilities = new javax.swing.JMenuItem();
        miExpenses = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pMain.setLayout(new java.awt.CardLayout());

        lblLoginTitle.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblLoginTitle.setText("Finance Keeper Login");
        lblLoginTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtUserID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUserID.setForeground(javax.swing.UIManager.getDefaults().getColor("textInactiveText"));
        txtUserID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserID.setText("Enter User ID...");
        txtUserID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserIDFocusLost(evt);
            }
        });

        pfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pfPassword.setText("Password");
        pfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfPasswordFocusLost(evt);
            }
        });

        btnLogin.setMnemonic('L');
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnExit.setMnemonic('E');
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblNewAcc.setForeground(java.awt.Color.blue);
        lblNewAcc.setText("Create an Account?...");
        lblNewAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewAccMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLoginLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLoginTitle)
                    .addGroup(pLoginLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserID)
                            .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(358, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNewAcc)
                .addGap(195, 195, 195))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblLoginTitle)
                .addGap(38, 38, 38)
                .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNewAcc)
                .addGap(48, 48, 48))
        );

        pMain.add(pLogin, "pLogin");

        lblOverview.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblOverview.setText("Overview");

        lblUtilityTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblUtilityTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtilityTitle.setText("Total Utilities");
        lblUtilityTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIncomeTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblIncomeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIncomeTitle.setText("Total Income");
        lblIncomeTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIncomeReturn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIncomeReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIncomeReturn.setText("Waiting for Total Income Value...");
        lblIncomeReturn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        lblUtilityReturn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUtilityReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtilityReturn.setText("Waiting for Total Utilities Value...");
        lblUtilityReturn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        lblExpensesTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblExpensesTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExpensesTitle.setText("Total Expenses");
        lblExpensesTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblExpReturn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblExpReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExpReturn.setText("Waiting for Total Expenses Value...");
        lblExpReturn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        lblSavedTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSavedTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSavedTitle.setText("Total Saved");
        lblSavedTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSavedReturn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSavedReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSavedReturn.setText("Waiting for Total Saved Income...");
        lblSavedReturn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout pnlStatisticsLayout = new javax.swing.GroupLayout(pnlStatistics);
        pnlStatistics.setLayout(pnlStatisticsLayout);
        pnlStatisticsLayout.setHorizontalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStatisticsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSavedReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblExpReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlStatisticsLayout.createSequentialGroup()
                        .addGroup(pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUtilityTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIncomeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExpensesTitle)
                            .addComponent(lblSavedTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblUtilityReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIncomeReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlStatisticsLayout.setVerticalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStatisticsLayout.createSequentialGroup()
                .addComponent(lblIncomeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIncomeReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUtilityTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUtilityReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExpensesTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExpReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSavedTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSavedReturn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAccounts.setMnemonic('A');
        btnAccounts.setText("Accounts");
        btnAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountsActionPerformed(evt);
            }
        });

        btnUtility.setMnemonic('U');
        btnUtility.setText("Utilities");
        btnUtility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtilityActionPerformed(evt);
            }
        });

        btnExpenses.setMnemonic('E');
        btnExpenses.setText("Expenses");
        btnExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpensesActionPerformed(evt);
            }
        });

        btnLogout.setMnemonic('L');
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnExit1.setMnemonic('E');
        btnExit1.setText("Exit");
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOptionsLayout = new javax.swing.GroupLayout(pnlOptions);
        pnlOptions.setLayout(pnlOptionsLayout);
        pnlOptionsLayout.setHorizontalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUtility, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnExit1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        pnlOptionsLayout.setVerticalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUtility, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pHomeLayout = new javax.swing.GroupLayout(pHome);
        pHome.setLayout(pHomeLayout);
        pHomeLayout.setHorizontalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
            .addGroup(pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pHomeLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblOverview)
                        .addComponent(pnlStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(pnlOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pHomeLayout.setVerticalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
            .addGroup(pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pHomeLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(lblOverview)
                    .addGap(18, 18, 18)
                    .addGroup(pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pnlOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(116, Short.MAX_VALUE)))
        );

        pMain.add(pHome, "pHome");

        pnlAccDetails.setPreferredSize(new java.awt.Dimension(187, 257));

        txtAccID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAccID.setForeground(java.awt.Color.gray);
        txtAccID.setText("Account ID...");

        txtForename.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtForename.setForeground(java.awt.Color.gray);
        txtForename.setText("Forename...");

        txtSurname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSurname.setForeground(java.awt.Color.gray);
        txtSurname.setText("Surname...");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setForeground(java.awt.Color.gray);
        txtEmail.setText("Email...");

        javax.swing.GroupLayout pnlAccDetailsLayout = new javax.swing.GroupLayout(pnlAccDetails);
        pnlAccDetails.setLayout(pnlAccDetailsLayout);
        pnlAccDetailsLayout.setHorizontalGroup(
            pnlAccDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAccDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAccID, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(txtForename, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSurname)
                    .addComponent(txtEmail))
                .addContainerGap())
        );
        pnlAccDetailsLayout.setVerticalGroup(
            pnlAccDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAccID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtForename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlIncome.setPreferredSize(new java.awt.Dimension(187, 45));

        txtIncome.setEditable(false);
        txtIncome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIncome.setForeground(java.awt.Color.gray);
        txtIncome.setText("Income...");

        txtTFA.setEditable(false);
        txtTFA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTFA.setForeground(java.awt.Color.gray);
        txtTFA.setText("Tax Free Allowance...");

        txtTT.setEditable(false);
        txtTT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTT.setForeground(java.awt.Color.gray);
        txtTT.setText("Total Taxable...");

        txtIT.setEditable(false);
        txtIT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIT.setForeground(java.awt.Color.gray);
        txtIT.setText("Income Tax...");

        txtNI.setEditable(false);
        txtNI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNI.setForeground(java.awt.Color.gray);
        txtNI.setText("National Insurance...");

        txtTD.setEditable(false);
        txtTD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTD.setForeground(java.awt.Color.gray);
        txtTD.setText("Total Deductions...");

        txtNW.setEditable(false);
        txtNW.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNW.setForeground(java.awt.Color.gray);
        txtNW.setText("Net Wage...");

        javax.swing.GroupLayout pnlIncomeLayout = new javax.swing.GroupLayout(pnlIncome);
        pnlIncome.setLayout(pnlIncomeLayout);
        pnlIncomeLayout.setHorizontalGroup(
            pnlIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIncomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIncome)
                    .addComponent(txtTFA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(txtTT)
                    .addComponent(txtIT)
                    .addComponent(txtNI)
                    .addComponent(txtTD)
                    .addComponent(txtNW))
                .addContainerGap())
        );
        pnlIncomeLayout.setVerticalGroup(
            pnlIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIncomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTFA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pAccountsLayout = new javax.swing.GroupLayout(pAccounts);
        pAccounts.setLayout(pAccountsLayout);
        pAccountsLayout.setHorizontalGroup(
            pAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAccDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pAccountsLayout.setVerticalGroup(
            pAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAccountsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlAccDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(pnlIncome, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                .addContainerGap())
        );

        pMain.add(pAccounts, "pAccounts");

        lblUtilities.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblUtilities.setText("Utilities");

        tblUtilities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Value", "Billing Cycle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spUtilities.setViewportView(tblUtilities);

        javax.swing.GroupLayout pUtilitiesLayout = new javax.swing.GroupLayout(pUtilities);
        pUtilities.setLayout(pUtilitiesLayout);
        pUtilitiesLayout.setHorizontalGroup(
            pUtilitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spUtilities, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
            .addGroup(pUtilitiesLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(lblUtilities)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pUtilitiesLayout.setVerticalGroup(
            pUtilitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUtilitiesLayout.createSequentialGroup()
                .addComponent(lblUtilities)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spUtilities, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
        );

        pMain.add(pUtilities, "pUtilities");

        tblExpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expense Item", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        spExpenses.setViewportView(tblExpenses);

        lblExpenses.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblExpenses.setText("Expenses");

        javax.swing.GroupLayout pExpensesLayout = new javax.swing.GroupLayout(pExpenses);
        pExpenses.setLayout(pExpensesLayout);
        pExpensesLayout.setHorizontalGroup(
            pExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
            .addGroup(pExpensesLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(lblExpenses)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pExpensesLayout.setVerticalGroup(
            pExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pExpensesLayout.createSequentialGroup()
                .addComponent(lblExpenses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
        );

        pMain.add(pExpenses, "pExpenses");

        lblNewLogin.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblNewLogin.setText("New Login");

        txtNewID.setForeground(java.awt.SystemColor.textInactiveText);
        txtNewID.setText("Enter your chosen ID...");

        pfNewPassword.setText("Password");
        pfNewPassword.setToolTipText("Enter your chosen password...");

        pfCheckPassword.setText("Password");

        javax.swing.GroupLayout pNewLoginLayout = new javax.swing.GroupLayout(pNewLogin);
        pNewLogin.setLayout(pNewLoginLayout);
        pNewLoginLayout.setHorizontalGroup(
            pNewLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNewLoginLayout.createSequentialGroup()
                .addGroup(pNewLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNewLoginLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(lblNewLogin))
                    .addGroup(pNewLoginLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addGroup(pNewLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNewID, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(pfNewPassword)
                            .addComponent(pfCheckPassword))))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        pNewLoginLayout.setVerticalGroup(
            pNewLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNewLoginLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(lblNewLogin)
                .addGap(46, 46, 46)
                .addComponent(txtNewID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(pfNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(pfCheckPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pMain.add(pNewLogin, "pNewLogin");

        mFile.setMnemonic('F');
        mFile.setText("File");

        miLogout.setMnemonic('L');
        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mFile.add(miLogout);

        miExit.setMnemonic('E');
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mFile.add(miExit);

        mbMenuBar.add(mFile);

        mEdit.setMnemonic('E');
        mEdit.setText("Edit");

        mExpenses.setMnemonic('E');
        mExpenses.setText("Expenses");

        miAdd.setMnemonic('A');
        miAdd.setText("Add New");
        mExpenses.add(miAdd);

        miEdit.setMnemonic('E');
        miEdit.setText("Edit");
        mExpenses.add(miEdit);

        miDelete.setMnemonic('D');
        miDelete.setText("Delete");
        mExpenses.add(miDelete);

        mEdit.add(mExpenses);

        mbMenuBar.add(mEdit);

        mNav.setMnemonic('N');
        mNav.setText("Navigate");

        miHome.setMnemonic('H');
        miHome.setText("Home");
        miHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHomeActionPerformed(evt);
            }
        });
        mNav.add(miHome);

        miAccounts.setMnemonic('A');
        miAccounts.setText("Accounts");
        miAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAccountsActionPerformed(evt);
            }
        });
        mNav.add(miAccounts);

        miUtilities.setMnemonic('U');
        miUtilities.setText("Utilities");
        miUtilities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUtilitiesActionPerformed(evt);
            }
        });
        mNav.add(miUtilities);

        miExpenses.setMnemonic('E');
        miExpenses.setText("Expenses");
        miExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExpensesActionPerformed(evt);
            }
        });
        mNav.add(miExpenses);

        mbMenuBar.add(mNav);

        mHelp.setMnemonic('H');
        mHelp.setText("Help");
        mHelp.setAlignmentX(1.0F);
        mHelp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        miAbout.setMnemonic('A');
        miAbout.setText("About");
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        mHelp.add(miAbout);

        mbMenuBar.add(mHelp);

        setJMenuBar(mbMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Version: v1.0"+"\n"+"Created By: Alex Morrison", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_miAboutActionPerformed

    private void miUtilitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUtilitiesActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pUtilities");
        miHome.setEnabled(true);
        miAccounts.setEnabled(true);
        miUtilities.setEnabled(false);
        miExpenses.setEnabled(true);
    }//GEN-LAST:event_miUtilitiesActionPerformed

    private void miAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAccountsActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pAccounts");
        miHome.setEnabled(true);
        miAccounts.setEnabled(false);
        miUtilities.setEnabled(true);
        miExpenses.setEnabled(true);
    }//GEN-LAST:event_miAccountsActionPerformed

    private void miHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHomeActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pHome");
        miHome.setEnabled(false);
        miAccounts.setEnabled(true);
        miUtilities.setEnabled(true);
        miExpenses.setEnabled(true);
        
    }//GEN-LAST:event_miHomeActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_miExitActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
        mNav.setEnabled(false);
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pLogin");
        
    }//GEN-LAST:event_miLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try{
            CardLayout card = (CardLayout)pMain.getLayout();
            int flag  = 1;
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/FinanceDB", "GateKeeper", "EyeOfSauron");
            Statement state = conn.createStatement();
            ResultSet res = state.executeQuery("Select ID, PASSWORD from LOGIN");
            while(res.next()) {
                if(res.getString(1).equals(txtUserID.getText()) && res.getString(2).equals(pfPassword.getText())) {
                    flag = 0;
                    break;
                }
            }
            if(flag == 0) {
                mNav.setEnabled(true);
                card.show(pMain, "pHome");
                miHome.setEnabled(false);
                txtUserID.setText("");
                pfPassword.setText("");
                btnLogin.setEnabled(false);
            }else {
                JOptionPane.showMessageDialog(null, "Login Error"+"\n"+"Reason: The User ID and/or Password was incorrect.", "Login Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void pfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPasswordFocusLost
        // TODO add your handling code here:
        if(pfPassword.getText().equals("")){
            pfPassword.setText("Password");
        }
    }//GEN-LAST:event_pfPasswordFocusLost

    private void pfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPasswordFocusGained
        // TODO add your handling code here:
        if(pfPassword.getText().equals("Password")){
            pfPassword.setText("");
        }
    }//GEN-LAST:event_pfPasswordFocusGained

    private void txtUserIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserIDFocusLost
        // TODO add your handling code here:
        if(txtUserID.getText().equals("")) {
            txtUserID.setText("Enter User ID...");
            txtUserID.setForeground(Color.LIGHT_GRAY);
            btnLogin.setEnabled(false);
        }else if(txtUserID.getText().equals("Enter User ID...")) {
            btnLogin.setEnabled(false);
        }else {
            btnLogin.setEnabled(true);
        }
    }//GEN-LAST:event_txtUserIDFocusLost

    private void txtUserIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserIDFocusGained
        // TODO add your handling code here:
        if(txtUserID.getText().equals("Enter User ID...")) {
            btnLogin.setEnabled(false);
            txtUserID.setText("");
            txtUserID.setForeground(Color.BLACK);
        }else {
            btnLogin.setEnabled(true);
        }
    }//GEN-LAST:event_txtUserIDFocusGained

    private void miExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExpensesActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pExpenses");
        miHome.setEnabled(true);
        miAccounts.setEnabled(true);
        miUtilities.setEnabled(true);
        miExpenses.setEnabled(false);
    }//GEN-LAST:event_miExpensesActionPerformed

    private void lblNewAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewAccMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pNewLogin");
    }//GEN-LAST:event_lblNewAccMouseClicked

    private void btnAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountsActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pAccounts");
        miHome.setEnabled(true);
        miAccounts.setEnabled(false);
        miUtilities.setEnabled(true);
        miExpenses.setEnabled(true);
    }//GEN-LAST:event_btnAccountsActionPerformed

    private void btnUtilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtilityActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pUtilities");
        miHome.setEnabled(true);
        miAccounts.setEnabled(true);
        miUtilities.setEnabled(false);
        miExpenses.setEnabled(true);
    }//GEN-LAST:event_btnUtilityActionPerformed

    private void btnExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpensesActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pExpenses");
        miHome.setEnabled(true);
        miAccounts.setEnabled(true);
        miUtilities.setEnabled(true);
        miExpenses.setEnabled(false);
    }//GEN-LAST:event_btnExpensesActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        mNav.setEnabled(false);
        CardLayout card = (CardLayout)pMain.getLayout();
        card.show(pMain, "pLogin");
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceKeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceKeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceKeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceKeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinanceKeeper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccounts;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnExpenses;
    public javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUtility;
    private javax.swing.JLabel lblExpReturn;
    private javax.swing.JLabel lblExpenses;
    private javax.swing.JLabel lblExpensesTitle;
    private javax.swing.JLabel lblIncomeReturn;
    private javax.swing.JLabel lblIncomeTitle;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblNewAcc;
    private javax.swing.JLabel lblNewLogin;
    private javax.swing.JLabel lblOverview;
    private javax.swing.JLabel lblSavedReturn;
    private javax.swing.JLabel lblSavedTitle;
    private javax.swing.JLabel lblUtilities;
    private javax.swing.JLabel lblUtilityReturn;
    private javax.swing.JLabel lblUtilityTitle;
    private javax.swing.JMenu mEdit;
    private javax.swing.JMenu mExpenses;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenu mNav;
    private javax.swing.JMenuBar mbMenuBar;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JMenuItem miAccounts;
    private javax.swing.JMenuItem miAdd;
    private javax.swing.JMenuItem miDelete;
    private javax.swing.JMenuItem miEdit;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miExpenses;
    private javax.swing.JMenuItem miHome;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miUtilities;
    private javax.swing.JPanel pAccounts;
    private javax.swing.JPanel pExpenses;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pNewLogin;
    private javax.swing.JPanel pUtilities;
    private javax.swing.JPasswordField pfCheckPassword;
    private javax.swing.JPasswordField pfNewPassword;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JPanel pnlAccDetails;
    private javax.swing.JPanel pnlIncome;
    private javax.swing.JPanel pnlOptions;
    private javax.swing.JPanel pnlStatistics;
    private javax.swing.JScrollPane spExpenses;
    private javax.swing.JScrollPane spUtilities;
    private javax.swing.JTable tblExpenses;
    private javax.swing.JTable tblUtilities;
    private javax.swing.JTextField txtAccID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtForename;
    private javax.swing.JTextField txtIT;
    private javax.swing.JTextField txtIncome;
    private javax.swing.JTextField txtNI;
    private javax.swing.JTextField txtNW;
    private javax.swing.JTextField txtNewID;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtTD;
    private javax.swing.JTextField txtTFA;
    private javax.swing.JTextField txtTT;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
